version: '3.5'

services:
  ya_service:
    container_name: yandex_service
    build:
      context: .
      dockerfile: ./Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5252:5252"
      - "5151:5151"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container_ya
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  postgres_data: